name: "HCL AppScan CodeSweep"
on:
  pull_request:
    types: [closed]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish issues to ASoC
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2.1
        with:
          service_url: https://cloud.appscan.com
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          publish_on_merge: true
          application_id: e76f8ec4-61a5-4ee5-bd63-a273c071eb16
          issue_status: New
          scan_base_name: CodeSweepActions  
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
