name: "HCL AppScan CodeSweep"
on:
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          service_url: https://cloud.appscan.com
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          publish_on_merge: true
          application_id: e76f8ec4-61a5-4ee5-bd63-a273c071eb16
          issue_status: New
          scan_base_name: CodeSweepActions  
      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2.1
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
